language: python
#sudo: false
os: 
  - linux
#  - osx
#  - windows
# choose python versions
python:
  - "3.6"
  - "3.7"
    #  - "2.7"

install:

  # Install miniconda
  # -----------------
  - PYTHON_TARGET=$TRAVIS_PYTHON_VERSION
  - echo $PYTHON_TARGET
  - if [[ $PYTHON_TARGET == 3* ]]; then
      export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3;
    fi
  - echo $CONDA_BASE
  - wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda update --quiet conda
  - ENV_NAME='test-environment'
  - conda create --quiet -n $ENV_NAME python=$PYTHON_TARGET
  - source activate $ENV_NAME

  # Customise the testing environment
  # ---------------------------------
  #install requirements from conda-forge based on conda-requirements.txt:
  - conda install -c conda-forge --quiet --file conda_requirements.txt
  #install pytest:
  - conda install -c conda-forge --quiet pytest
  # install packages directly from github:
  - pip install git+https://github.com/mheikenfeld/piecharts.git
  - pip install git+https://github.com/mheikenfeld/mpdiag.git

  - PREFIX=$HOME/miniconda/envs/$ENV_NAME

  # Output debug info
  - conda list
  - conda info -a

  # Install
  - pip install .

  # Output debug info
  - conda list

# command to run tests
#script
script:
  - pytest

